### ISSUE TITLE
Document using a lease

### ISSUE THREAD

**Issue by mcassaniti** [martyanov/aetcd#31]
I'm attempting to create a lease, make sure it is refreshed and set an event if the lease expires. I don't think the below code is correct but it is what I have so far. There's no documentation on using a lease correctly (yet).

```python

LEASE_TTL = 5

client = Client(host=args.host, port=args.port)
lease  = await client.lease(LEASE_TTL)
lease_dropped = asyncio.Event()

async def hold_lease(lease, lease_dropped_event):
    '''
    Maintain a lease for the duration of the process.
    If the lease is dropped then set the event.
    Run this function in a separate task.
    '''

    while True:
        try:
            await sleep(await lease.remaining_ttl() / 2.0)
            await lease.refresh()
            if await lease.granted_ttl() == 0:
                raise Exception('Lease dropped')
        except:
            lease_dropped.set()
            break
```

Can anyone provide some feedback on this so I can make sure I don't falsely refresh expired leases?

**Comment by tamirOK** [comment]
I would do it like this:

```python

LEASE_TTL = 5

client = Client(host=args.host, port=args.port)
lease  = await client.lease(LEASE_TTL)
lease_dropped = asyncio.Event()

async def hold_lease(lease, lease_dropped_event):
    '''
    Maintain a lease for the duration of the process.
    If the lease is dropped then set the event.
    Run this function in a separate task.
    '''

    try:
        while True:
            result = await client.refresh_lease(lease.id)
            if result.TTL == 0:  # if lease expired
                lease_dropped.set()
                raise Exception('Lease dropped')
            await asyncio.sleep(result.TTL / 2)
    except aetcd.ClientError as e:
        lease_dropped_event.set()
        raise Exception(f'Failed ETCD operation with error: {e!r}')

```

**Comment by martyanov** [comment]
@mcassaniti `aetcd` tries to be as low level as possible wrapper over `etcd` RPC. The lease is documented [here](https://aetcd.readthedocs.io/en/latest/reference.html#aetcd.client.Client.lease) and [here](https://aetcd.readthedocs.io/en/latest/reference.html#aetcd.leases.Lease).

How to use it correctly really depends on your project requirements, usually there is some coroutine that maintains lease freshness and raises an error if refresh fails, something like @tamirOK suggested.

**Comment by martyanov** [comment]
@mcassaniti a bit of clarification. There is no need to make 2 RPC calls, just call `refresh` and check the liveness.

**Comment by martyanov** [comment]
I think we should implement sort of `LeaseRefreshResult` and document its attributes, now it is just an underlying `protobuf` response. It is documented [here](https://etcd.io/docs/v3.5/learning/api/#lease-api).

**Comment by martyanov** [comment]
Also, maybe it make sense to raise `LeaseExpiredError` if `refresh` returned `TTL` equals to 0.

**Comment by tamirOK** [comment]
> Also, maybe it make sense to raise `LeaseExpiredError` if `refresh` returned `TTL` equal to 0.

`TTL` is 0 for non-existent lease_id, too

**Comment by mcassaniti** [comment]
`LeaseExpiredError` sounds great. Thanks for the feedback and documentation pointers.

**Comment by mcassaniti** [comment]
You've used `client.refresh_lease()`. Now perhaps I didn't look hard enough but I couldn't find that in the reference guide.

**Comment by martyanov** [comment]
We'll fix the docs, thanks for the feedback.
